; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]

default_envs = lamp


[env]

platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200


[env:core]

build_flags =
    -D DEVICE_ROLE_CORE


[env:main]

build_flags =
    -D DEVICE_ROLE_MAIN


[env:lamp]

build_flags =
    -D DEVICE_ROLE_LAMP


[env:relay]

build_flags =
    -D DEVICE_ROLE_RELAY


[env:lamp_a]

build_flags =
    -D DEVICE_LAMP_A


[env:lamp_b]

build_flags =
    -D DEVICE_LAMP_B